
#dtplyr; lets fans of tidyverse's dplyr syntax access data.table speed on the back end, all without having to learn a new format for their code
# dtplyr is a good tool to translate dplyr version of code into data.table syntax


library(dplyr)
library(data.table)
library(dtplyr)
library(readr)


library(hflights)

colnames(hflights)

dim(hflights)


#Average Arrival Delay with dplyr package

delay_summary <- hflights %>% 
  group_by(Dest, UniqueCarrier) %>% 
  summarize(
    AvgDelay = mean(ArrDelay)
  ) %>% 
  arrange(Dest, desc(AvgDelay))
  


# With dtplyr first creat lazy datatable version of data with lazy_dt then run ur usual dplyr  code, then turn the result
# back into a dataframe, tibble or, data  table

flight_delay_lazy <- lazy_dt(hflights)

class(flight_delay_lazy) # this lazy object is dtplyr step object

print(flight_delay_lazy)

# now dtplyr synatx on my lazy object

 


delay_summary_dtplyr <- flight_delay_lazy %>% 
  group_by(Dest, UniqueCarrier) %>% 
  summarize(
    AvgDelay = mean(ArrDelay)
  ) %>% 
  arrange(Dest, desc(AvgDelay)) %>% as_tibble()
  
print(delay_summary_dtplyr) # Here Call: _DT1 shows in print that ot is data.table code generated by dtplyr



# now running that code with same commands using data.table pkg


mydt <- as.data.table(hflights) # creating datatable

#now copying my Datatable code from the output of print(delay_summary_dtplyr) where Call contains datatable syntax cfor dtplyr code
# which is this :-- Call:   `_DT1`[, .(AvgDelay = mean(ArrDelay)), keyby = .(Dest, UniqueCarrier)][order(Dest, -AvgDelay)]

# now only replace `_DT1` with my data.table object which here is mydt

x <- mydt[, .(AvgDelay = mean(ArrDelay)), keyby = .(Dest, UniqueCarrier)][order(Dest, 
                                                                                     -AvgDelay)]
x










































